cast_table = {
    "byte": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
             "long": "explicit", "float": "explicit", "double": "explicit"},
    "short": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
              "long": "explicit", "float": "explicit", "double": "explicit"},
    "char": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
             "long": "explicit", "float": "explicit", "double": "explicit"},
    "int": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
            "long": "explicit", "float": "explicit", "double": "explicit"},
    "long": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
             "long": "explicit", "float": "explicit", "double": "explicit"},
    "float": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
              "long": "explicit", "float": "explicit", "double": "explicit"},
    "double": {"byte": "explicit", "short": "explicit", "char": "explicit", "int": "explicit",
               "long": "explicit", "float": "explicit", "double": "explicit"},

    "text": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
             "constant_keyword": "implicit", "wildcard": "implicit"},
    "string": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
               "constant_keyword": "implicit", "wildcard": "implicit"},
    "match_only_text": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
                        "constant_keyword": "implicit", "wildcard": "implicit"},
    "keyword": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
                "constant_keyword": "implicit", "wildcard": "implicit"},
    "constant_keyword": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
                         "constant_keyword": "implicit", "wildcard": "implicit"},
    "wildcard": {"text": "implicit", "string": "implicit", "match_only_text": "implicit", "keyword": "implicit",
                 "constant_keyword": "implicit", "wildcard": "implicit"},

    "_complex": {"object": "implicit"},
    "object": {"_complex": "implicit"},  # DEV'S PROBLEM, FIELDS IN COMPLEX MUST HAVE DEFAULT VALUES IF NOT PROVIDED
}
